version: '3.8'

services:
  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: myapp
    ports:
      - "8080:8080"
    environment:
      MYSQL_DSN: "root:root@tcp(mysql:3306)/shop?parseTime=true"
      REDIS_ADDR: "localhost:6379"
      KAFKA_BROKERS: "localhost:9092"
      ELASTICSEARCH_URL: "http://localhost:9200"

networks:
  default:
    driver: bridge
